# Generated by Django 2.1.7 on 2019-02-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_color', models.CharField(max_length=10)),
                ('autopilot', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('card_number', models.CharField(max_length=16)),
                ('card_date', models.CharField(max_length=10)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Engine')),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Interior')),
                ('wheels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Wheels')),
            ],
        ),
    ]
